services:
   laravel:
      container_name: laravel
      image: bitnami/laravel:latest
      volumes:
         - ./backend:/app
      ports:
         - "8000:8000"

      networks:
         - main-network
      restart: on-failure

networks:
   main-network:
      driver: bridge
